### ISSUE TITLE
How to deal with virtual evidences in DBN?

### ISSUE THREAD

**Issue by lemonmachine** [pgmpy/pgmpy#1629]
Hi everyone, I have been trying to use pgmpy for dynamic Bayesian network inference recently. I noticed that static Bayesian networks in pgmpy are capable of handling virtual evidence, but dynamic Bayesian networks are not currently supported. 
I found that the inference algorithm for dynamic Bayesian networks is actually based on static belief propagation after reading the source code. Perhaps virtual evidence inference in DBNs could be achieved by modifying the algorithm. However, I am not sure if it can be implemented. 
Does anyone know how to handle virtual evidence in DBN?  If you are also considering this issue, we can exchange ideas. Thanks a lot for any help!:)

**Comment by ankurankan** [comment]
@lemonmachine Sorry for the late reply. The virtual evidence option isn't integrated into DBN inference yet. But you can use Approximate Inference to get approx inference results with virtual evidence. Please make sure to use the latest dev branch as I have pushed some bug fixes. Example:
```python
        from pgmpy.models import DynamicBayesianNetwork as DBN
        from pgmpy.factors.discrete import TabularCPD
        from pgmpy.inference import ApproxInference
        model = DBN()
        model.add_edges_from(
            [(("Z", 0), ("X", 0)), (("X", 0), ("Y", 0)), (("Z", 0), ("Z", 1))]
        )
        z_start_cpd = TabularCPD(("Z", 0), 2, [[0.5], [0.5]])
        x_i_cpd = TabularCPD(
            ("X", 0),
            2,
            [[0.6, 0.9], [0.4, 0.1]],
            evidence=[("Z", 0)],
            evidence_card=[2],
        )
        y_i_cpd = TabularCPD(
            ("Y", 0),
            2,
            [[0.2, 0.3], [0.8, 0.7]],
            evidence=[("X", 0)],
            evidence_card=[2],
        )
        z_trans_cpd = TabularCPD(
            ("Z", 1),
            2,
            [[0.4, 0.7], [0.6, 0.3]],
            evidence=[("Z", 0)],
            evidence_card=[2],
        )
        model.add_cpds(z_start_cpd, z_trans_cpd, x_i_cpd, y_i_cpd)
        model.initialize_initial_state()
        infer = ApproxInference(model)
        infer.query(
            [("Y", 4)], virtual_evidence=[TabularCPD(("Y", 2), 2, [[0.2], [0.8]])]
        )
```

**Comment by lemonmachine** [comment]
> @lemonmachine Sorry for the late reply. The virtual evidence option isn't integrated into DBN inference yet. But you can use Approximate Inference to get approx inference results with virtual evidence. Please make sure to use the latest dev branch as I have pushed some bug fixes. Example:
> 
> ```python
>         from pgmpy.models import DynamicBayesianNetwork as DBN
>         from pgmpy.factors.discrete import TabularCPD
>         from pgmpy.inference import ApproxInference
>         model = DBN()
>         model.add_edges_from(
>             [(("Z", 0), ("X", 0)), (("X", 0), ("Y", 0)), (("Z", 0), ("Z", 1))]
>         )
>         z_start_cpd = TabularCPD(("Z", 0), 2, [[0.5], [0.5]])
>         x_i_cpd = TabularCPD(
>             ("X", 0),
>             2,
>             [[0.6, 0.9], [0.4, 0.1]],
>             evidence=[("Z", 0)],
>             evidence_card=[2],
>         )
>         y_i_cpd = TabularCPD(
>             ("Y", 0),
>             2,
>             [[0.2, 0.3], [0.8, 0.7]],
>             evidence=[("X", 0)],
>             evidence_card=[2],
>         )
>         z_trans_cpd = TabularCPD(
>             ("Z", 1),
>             2,
>             [[0.4, 0.7], [0.6, 0.3]],
>             evidence=[("Z", 0)],
>             evidence_card=[2],
>         )
>         model.add_cpds(z_start_cpd, z_trans_cpd, x_i_cpd, y_i_cpd)
>         model.initialize_initial_state()
>         infer = ApproxInference(model)
>         infer.query(
>             [("Y", 4)], virtual_evidence=[TabularCPD(("Y", 2), 2, [[0.2], [0.8]])]
>         )
> ```

Thank you very much for the reply! This is very helpful to me :)

**Comment by lemonmachine** [comment]
> @lemonmachine Sorry for the late reply. The virtual evidence option isn't integrated into DBN inference yet. But you can use Approximate Inference to get approx inference results with virtual evidence. Please make sure to use the latest dev branch as I have pushed some bug fixes. Example:
> 
> ```python
>         from pgmpy.models import DynamicBayesianNetwork as DBN
>         from pgmpy.factors.discrete import TabularCPD
>         from pgmpy.inference import ApproxInference
>         model = DBN()
>         model.add_edges_from(
>             [(("Z", 0), ("X", 0)), (("X", 0), ("Y", 0)), (("Z", 0), ("Z", 1))]
>         )
>         z_start_cpd = TabularCPD(("Z", 0), 2, [[0.5], [0.5]])
>         x_i_cpd = TabularCPD(
>             ("X", 0),
>             2,
>             [[0.6, 0.9], [0.4, 0.1]],
>             evidence=[("Z", 0)],
>             evidence_card=[2],
>         )
>         y_i_cpd = TabularCPD(
>             ("Y", 0),
>             2,
>             [[0.2, 0.3], [0.8, 0.7]],
>             evidence=[("X", 0)],
>             evidence_card=[2],
>         )
>         z_trans_cpd = TabularCPD(
>             ("Z", 1),
>             2,
>             [[0.4, 0.7], [0.6, 0.3]],
>             evidence=[("Z", 0)],
>             evidence_card=[2],
>         )
>         model.add_cpds(z_start_cpd, z_trans_cpd, x_i_cpd, y_i_cpd)
>         model.initialize_initial_state()
>         infer = ApproxInference(model)
>         infer.query(
>             [("Y", 4)], virtual_evidence=[TabularCPD(("Y", 2), 2, [[0.2], [0.8]])]
>         )
> ```

Thank you very much for your reply, but I encountered an error when trying to run the code. I am using the latest version of pgmpy.Here is the error：
Traceback (most recent call last):
  File "D:\pythonproject\threat assessment\virtual evidence.py", line 34, in <module>
    infer.query(
  File "D:\pythonproject\venv\lib\site-packages\pgmpy\inference\ApproxInference.py", line 131, in query
    return self.get_distribution(samples, variables=variables, joint=joint)
  File "D:\pythonproject\venv\lib\site-packages\pgmpy\inference\ApproxInference.py", line 61, in get_distribution
    samples.groupby(variables).size() / samples.shape[0]
  File "D:\pythonproject\venv\lib\site-packages\pandas\core\frame.py", line 8402, in groupby
    return DataFrameGroupBy(
  File "D:\pythonproject\venv\lib\site-packages\pandas\core\groupby\groupby.py", line 965, in __init__
    grouper, exclusions, obj = get_grouper(
  File "D:\pythonproject\venv\lib\site-packages\pandas\core\groupby\grouper.py", line 888, in get_grouper
    raise KeyError(gpr)
KeyError: ('Y', 4)

**Comment by ankurankan** [comment]
@lemonmachine You will need to install the dev branch from github using:
```
pip install git+https://github.com/pgmpy/pgmpy.git@dev
```

**Comment by lemonmachine** [comment]
> @lemonmachine You will need to install the dev branch from github using:
> 
> ```
> pip install git+https://github.com/pgmpy/pgmpy.git@dev
> ```

I'm sorry to bother you again. I followed the method you suggested to install, but the code still cannot run, and I really don't know why. Here is the error message:
  0%|          | 0/15 [00:00<?, ?it/s]
  By the way, I would like to ask if there are any plans to add virtual evidence option to the DBN exact inference algorithm in the future?:)
